### ISSUE TITLE
Display Task exit code when "done"

### ISSUE THREAD

**Issue by alanbchristie** [InformaticsMatters/squonk2-data-manager-ui#1320]
Job **Task** objects contain an `exit_code`.

It would be valuable if we could see this when the **Task** is `done`, maybe on the coin/job bar?

![image](https://github.com/InformaticsMatters/squonk2-data-manager-ui/assets/29806285/c33758cb-1c77-4646-a21d-97f19bc80f73)

**Comment by alanbchristie** [comment]
If I add it as an event it will be automatic I guess? i.e. **Finished (0)**? Just thought a distinct exit code might have bene useful, maybe not.

**Comment by OliverDudgeon** [comment]
Implemented this as originally proposed
