### ISSUE TITLE
Additional ways to input files

### ISSUE THREAD

**Issue by OliverDudgeon** [InformaticsMatters/squonk2-data-manager-ui#876]
There are a couple of extra input flows that would be nice for the UI to support. Currently, **Requires an API change**. 

The UI needs the option for two input methods. File selector and molecule sketching. Whether an input supports SMILES input would be a field in the input schema. The default method when SMILES input is allowed should be the SMILES input, otherwise file inputs is always used.

The two possible ways this can be used are:

- Allow text input for SMILES (copy and paste SMILES)

Simple text input that allows input of smiles.
Maybe visualize these? Fragnet-Viz endpoint or in the Sketcher?

- Molecule sketcher (Draw a molecule to generate smiles)

~Existing molecule sketcher. Would need to be migrated from Fragnet search to react-sci-components.~ Will implement a more modern scetcher with react bindings (https://github.com/epam/ketcher). Input would default to a text field described above but with a button to the right that would open a sketcher widget (this could be an expanding region like the file input but also could be a popup). The user would then sketch the molecule and the textfield would get the SMILES output as it is generated. A close button would then hide the widget. Additionally, it would be nice for there to be some sketcher state that is scoped to all inputs. This would make it easier to have multiple inputs that have similar inputs.

**Comment by tdudgeon** [comment]
We've worked out how the job can handle this alternative input.
The prototype is the [similarity-screen-file](https://github.com/InformaticsMatters/virtual-screening/blob/main/data-manager/rdkit.yaml#L932) job.
The `queryFile` input would change to be of `type` `molecules`.
The UI would handle that by allowing the user to do one of the following:
1. specify a project file
2. type or C&P one or more SMILES
3. use sketcher to generate one or more SMILES.

If the first case the value sent in the request should look like this: `file://path/to/file.smi`.

In the second and third cases the value would be a string containing the SMILES separated by newline. e.g. `smiles1\nsmiles2\nsmiles3`

Limitations that we might address in future:
1. Only molecules as SMILES. MIght allow other formats at a later time
2. Will blow up if the string is very long, but we document this as only beiong suitable for a small number of molecules, and can add `minValues` and `maxValues` attributes to control this at a later stage.
