### ISSUE TITLE
Strange error from rdkit-molprops job

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/squonk2-data-manager-ui#952]
This bad error is seen when opening the rdkit-molprops job on the AWS prod system.

![image](https://user-images.githubusercontent.com/647419/227490233-a37bcf21-125c-4554-ac39-f15dbde88dc7.png)

It is not seen on DLS dev where the versions of the UI and the job seem to be identical.
Any thoughts on what the error means?

**Comment by OliverDudgeon** [comment]
There's an error in the job schema. The "idColumn" field has an array (`["string"]`) as its type. I presume the correct shecma should be:
```
"idColumn": {
  "title": "Index (text) or name (SDF) to use for the ID field",
  "type": "string",
  "pattern": "^[A-Za-z0-9_\\.\\- ]+$"
},
```

With this, the schema runs fine in the [RJSF sandbox](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJoYWMiOnRydWUsIm51bVJvdEJvbmRzIjp0cnVlLCJudW1SaW5ncyI6dHJ1ZSwibnVtQXJvUmluZ3MiOnRydWUsIm51bUNoaXJhbENlbnRyZXMiOnRydWUsIm51bVVuZGVmQ2hpcmFsQ2VudHJlcyI6dHJ1ZSwibnVtU1AzIjp0cnVlLCJsb2dwIjp0cnVlLCJ0cHNhIjp0cnVlLCJzZXBhcmF0b3IiOiJ0YWIiLCJzZGZSZWFkUmVjb3JkcyI6MTAwLCJvdXRwdXRGaWxlIjoiYmxhaC5wbmcifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJvdXRwdXRGaWxlIl0sInByb3BlcnRpZXMiOnsib3V0cHV0RmlsZSI6eyJ0aXRsZSI6Ik91dHB1dCBmaWxlIG5hbWUiLCJ0eXBlIjoic3RyaW5nIiwicGF0dGVybiI6Il5bQS1aYS16MC05Xy9cXC5cXC1dKyQifSwiaGFjIjp7InRpdGxlIjoiQ2FsY3VsYXRlIGhlYXZ5IGF0b20gY291bnQiLCJ0eXBlIjoiYm9vbGVhbiIsImRlZmF1bHQiOnRydWV9LCJudW1Sb3RCb25kcyI6eyJ0aXRsZSI6IkNhbGN1bGF0ZSBudW1iZXIgb2Ygcm90YXRhYmxlIGJvbmRzIiwidHlwZSI6ImJvb2xlYW4iLCJkZWZhdWx0Ijp0cnVlfSwibnVtUmluZ3MiOnsidGl0bGUiOiJDYWxjdWxhdGUgbnVtYmVyIG9mIHJpbmdzIiwidHlwZSI6ImJvb2xlYW4iLCJkZWZhdWx0Ijp0cnVlfSwibnVtQXJvUmluZ3MiOnsidGl0bGUiOiJDYWxjdWxhdGUgbnVtYmVyIG9mIGFyb21hdGljIHJpbmdzIiwidHlwZSI6ImJvb2xlYW4iLCJkZWZhdWx0Ijp0cnVlfSwibnVtQ2hpcmFsQ2VudHJlcyI6eyJ0aXRsZSI6IkNhbGN1bGF0ZSBudW1iZXIgb2YgY2hpcmFsIGNlbnRyZXMiLCJ0eXBlIjoiYm9vbGVhbiIsImRlZmF1bHQiOnRydWV9LCJudW1VbmRlZkNoaXJhbENlbnRyZXMiOnsidGl0bGUiOiJDYWxjdWxhdGUgbnVtYmVyIG9mIHVuZGVmaW5lZCBjaGlyYWwgY2VudHJlcyIsInR5cGUiOiJib29sZWFuIiwiZGVmYXVsdCI6dHJ1ZX0sIm51bVNQMyI6eyJ0aXRsZSI6IkNhbGN1bGF0ZSBudW1iZXIgb2YgU1AzIGh5YnJpZGlzZWQgY2FyYm9uIGF0b21zIiwidHlwZSI6ImJvb2xlYW4iLCJkZWZhdWx0Ijp0cnVlfSwibG9ncCI6eyJ0aXRsZSI6IkNhbGN1bGF0ZSBDcmlwcGVuIGxvZ1AiLCJ0eXBlIjoiYm9vbGVhbiIsImRlZmF1bHQiOnRydWV9LCJ0cHNhIjp7InRpdGxlIjoiQ2FsY3VsYXRlIHRvcG9sb2dpY2FsIHBvbGFyIHN1cmZhY2UgYXJlYSIsInR5cGUiOiJib29sZWFuIiwiZGVmYXVsdCI6dHJ1ZX0sInJlYWRIZWFkZXIiOnsidGl0bGUiOiJJbnB1dCBoYXMgaGVhZGVyIGxpbmUgKHRleHQgZm9ybWF0cyBvbmx5KSIsInR5cGUiOiJib29sZWFuIn0sIndyaXRlSGVhZGVyIjp7InRpdGxlIjoiT3V0cHV0IGhhcyBoZWFkZXIgbGluZSAodGV4dCBmb3JtYXRzIG9ubHkpIiwidHlwZSI6ImJvb2xlYW4ifSwic2VwYXJhdG9yIjp7InRpdGxlIjoiU2VwYXJhdG9yIGZvciB0ZXh0IGZvcm1hdHMiLCJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6InRhYiIsImVudW0iOlsidGFiIiwiY29tbWEiLCJzcGFjZSIsInBpcGUiXX0sImlkQ29sdW1uIjp7InRpdGxlIjoiSW5kZXggKHRleHQpIG9yIG5hbWUgKFNERikgdG8gdXNlIGZvciB0aGUgSUQgZmllbGQiLCJ0eXBlIjoic3RyaW5nIiwicGF0dGVybiI6Il5bQS1aYS16MC05X1xcLlxcLSBdKyQifSwic2RmUmVhZFJlY29yZHMiOnsidGl0bGUiOiJOdW1iZXIgb2YgU0RGIHJlY29yZHMgdG8gcmVhZCBmaWVsZCBuYW1lcyIsInR5cGUiOiJpbnRlZ2VyIiwiZGVmYXVsdCI6MTAwfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) when it didn't work properly before.

**Comment by tdudgeon** [comment]
Good spot. I looked for something like that but didn't see it.
Now fixed.
