### ISSUE TITLE
Browser view does not seem to work when files are at the root

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/squonk2-data-manager-ui#953]
If you run a job that generates a PNG file then trying to view that output using the browser view seems to fail.
If you view it from the project tab with the browser view it works OK.
The error you see is:
```
{
"detail": "'' is too short\n\nFailed validating 'minLength' in schema:\n    {'example': '/',\n     'maxLength': 260,\n     'minLength': 1,\n     'pattern': '^(/[A-Za-z0-9-_.]+)+$|^/$',\n     'type': 'string'}\n\nOn instance:\n    ''",
"status": 400,
"title": "Bad Request",
"type": "about:blank"
}
```

To generate such output run the `pk-tmax-cmax-sim` job on the IM/PROD site with these options:
  half-life = 0.79
  absorption = 0.5
  dose = 0.14
  auc = 0.88
  time = 8.0

**Comment by OliverDudgeon** [comment]
This was a wider issues for files at the directory root. However, I remeber this working in the past. Did the API become more strict? 

The UI is making requests with `?file=browserviewertest.json&path=`. Removing the `&path=` makes it work. Should the API here understand that an empty string is assumed to the project root? @tdudgeon @alanbchristie 

Anyway there's a fix coming now...
